services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    restart: unless-stopped
    ports:
      - 139:139
      - 445:445
    environment:
      - TZ=Asia/Shanghai
      - USER=tom
      - PASS=95816
      - UID=1000
      - GID=100
      - NAME=Storage
    volumes:
      - /mnt/common/shares:/storage/shares
      - /mnt/movies/library:/storage/movies:ro     
      - /mnt/series/library:/storage/series:ro