services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
      WEBUI_PORT: 8081
    ports:
      - 8081:8081
      - 10881:10881
      - 10881:10881/udp
    volumes:
      - ./config:/config/qBittorrent
      - /mnt/common/shares/downloads:/downloads