services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PUID: 1000
      PGID: 1000
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    ports:
      # - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config:/config/qBittorrent
      - /mnt/common/shares/downloads:/downloads
    networks:
      - webnet

networks:
  webnet:
    external: true
