services:
  clash:
    image: dreamacro/clash:latest
    container_name: clash
    volumes:
      - ./config:/root/.config/clash
    ports:
      - "7890:7890/tcp"
      - "7890:7890/udp"
      - "9090:9090"
    restart: unless-stopped

  clash-dashboard:
    image: centralx/clash-dashboard
    container_name: clash-dashboard
    ports:
      - "7880:80"
    restart: unless-stopped
