services:
  stirlingpdf:
    container_name: stirlingpdf
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    volumes:
      # - ./volumes/tessdata:/usr/share/tessdata   # OCR language files
      - ./volumes/configs:/configs               # Settings & database
      - ./volumes/logs:/logs                     # Application logs
      - ./volumes/pipeline:/pipeline             # Automation configs
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - HTTP_PROXY=http://forward-proxy:7890
      - HTTPS_PROXY=http://forward-proxy:7890
      - SECURITY_ENABLELOGIN=false
      - LANGS=zh_CN
    networks:
      - webnet

networks:
  webnet:
    external: true
