services:
  ubuntu:
    image: liuyuchuan/ubuntu:latest
    container_name: ubuntu
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /home/tom/code:/home/develop/code
      - /home/tom/.ssh:/home/develop/.ssh:ro
      - /home/tom/.gitconfig:/home/develop/.gitconfig:ro
    ports:
      - 2222:22
      - 3000:3000
    restart: unless-stopped
