services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /run/udev:/run/udev:ro
      - ./volumes/config:/opt/scrutiny/config
      - ./volumes//influxdb:/opt/scrutiny/influxdb
    ports:
      - 8080:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
    restart: unless-stopped