services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443" # 为后续 HTTPS 准备
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-config/logs:/var/log/nginx
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    external: true
