services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    command: glances -w # -w 参数代表启动 Web 服务模式
    # ports:
    #   - 61208:61208 # 网页访问端口
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # 允许监控 Docker 容器
      # - /sys/class/thermal:/sys/class/thermal:ro # 挂载温度传感器接口（可选）
      - /proc:/host/proc:ro # 读取进程信息
      - /:/mnt:ro # 只读挂载根目录，用于读取磁盘信息
    environment:
      - GLANCES_OPT="-w --port 61208" # 环境变量方式指定参数
    networks:
      - webnet

networks:
  webnet:
    external: true
