# admin:liuyuchuan95816
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    # ports:
    #   - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/data:/app/data
      # 映射所有 Stacks
      - /home/tom/nas:/home/tom/nas
    environment:
      #  docker compose 文件路径
      - DOCKGE_STACKS_DIR=/home/tom/nas
    networks:
      - webnet
networks:
  webnet:
    external: true
